tittle: "My new blog" 
description: "Blog test created with the Jejyll hacker theme"
url: "https://AngelicaMariaGranados-cyber.github.io/demo"
signoff: "Angelica"

Links: 
-name:     Posts
	url:      /
	external: false
-name:     Sobre mi 
	url:       /about
	external:  false

permalink:   /posts/:title

defaults:
-values:
	layout: "default"
	
